### ISSUE TITLE
Not working on ElasticSearch 5?

### ISSUE THREAD

**Issue by motourer** [macbre/phantomas-reporter-elasticsearch#2]
Hi, 
Just wondering if I am doing something wrong, or if the reporter does not work with ElasticSearch 5.x? 
I have the reporter working with ElasticSearch 2.4.x, but no luck on 5.x.
Is there a plan to support 5.x in future, if not currently?
Thanks,
Patrick

**Comment by AdriwanKenoby** [comment]
Neither on Elasticsearch 6 then ...

**Comment by AdriwanKenoby** [comment]
Hi @macbre, 

maybe just update your package.json dependency to make it work with the latest elastisearch JS API , nowday 14.1.0. for compatibility with Elasticsearch 6

**Comment by AdriwanKenoby** [comment]
@motourer, I have made a fork wich work on latest ES6, see [https://github.com/macbre/phantomas-reporter-elasticsearch/pull/4](PR)

**Comment by motourer** [comment]
@AdriwanKenoby - that sounds really great. Thanks. On my next project I'll be sure to checkout the phantomas-reporter-elasticsearch again. For the current project I ended up using curl to upload the report to elasticsearch, which is working fine.

**Comment by macbre** [comment]
Fixed thanks to #4
